// frontend/src/pages/Dashboard.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import ItemCard from '../components/ItemCard';
import { Search, Filter, Compass } from 'lucide-react';

const Dashboard = () => {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState('All');
    const [searchTerm, setSearchTerm] = useState('');
    const { user } = useAuth();

    useEffect(() => {
        fetchItems();
    }, [filter]);

    const fetchItems = async () => {
        setLoading(true);
        try {
            let url = '/api/items';
            if (filter !== 'All') {
                url += `?category=${filter}`;
            }
            const { data } = await axios.get(url);
            setItems(data);
        } catch (error) {
            console.error('Failed to fetch items:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleSearch = async (e) => {
        e.preventDefault();
        setLoading(true);
        try {
            let url = `/api/items?search=${searchTerm}`;
            if (filter !== 'All') url += `&category=${filter}`;
            const { data } = await axios.get(url);
            setItems(data);
        } catch (error) {
            console.error('Failed to search items:', error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="animate-fade-in pb-12">
            <div className="mb-10 text-center max-w-2xl mx-auto mt-6">
                <div className="inline-flex items-center justify-center p-3 bg-[#f8f9fa] rounded-full mb-4">
                    <Compass className="text-gray-600" size={28} />
                </div>
                <h1 className="text-3xl font-extrabold text-gray-800 mb-3">Community Board</h1>
                <p className="text-gray-500">Browse reported missing and found items around the community.</p>
            </div>

            <div className="bg-white p-4 rounded-3xl subtle-shadow mb-8 flex flex-col md:flex-row gap-4 items-center justify-between">
                <div className="flex w-full md:w-auto p-1 bg-gray-50 rounded-full border border-gray-100">
                    {['All', 'Lost', 'Found'].map(cat => (
                        <button
                            key={cat}
                            onClick={() => setFilter(cat)}
                            className={`px-6 py-2 rounded-full text-sm font-bold transition-all ${filter === cat
                                    ? cat === 'Lost' ? 'bg-[#ffeaf0] text-[var(--color-primary)] shadow-sm'
                                        : cat === 'Found' ? 'bg-[#eaf3ff] text-[var(--color-secondary)] shadow-sm'
                                            : 'bg-white text-gray-800 shadow-sm'
                                    : 'text-gray-500 hover:text-gray-700'
                                }`}
                        >
                            {cat}
                        </button>
                    ))}
                </div>

                <form onSubmit={handleSearch} className="relative w-full md:w-80">
                    <input
                        type="text"
                        placeholder="Search items..."
                        className="w-full bg-gray-50 border-none rounded-full py-3 pl-5 pr-12 text-sm focus:ring-2 focus:ring-[var(--color-secondary)] focus:bg-white transition-all outline-none"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                    <button type="submit" className="absolute right-2 top-1.5 p-1.5 bg-gray-200 text-gray-600 rounded-full hover:bg-gray-300 transition-colors">
                        <Search size={18} />
                    </button>
                </form>
            </div>

            {loading ? (
                <div className="flex justify-center my-20">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[var(--color-primary)]"></div>
                </div>
            ) : items.length === 0 ? (
                <div className="text-center py-20 bg-white rounded-3xl subtle-shadow border border-gray-50 flex flex-col items-center">
                    <div className="bg-gray-50 w-20 h-20 rounded-full flex items-center justify-center mb-4">
                        <Filter className="text-gray-300" size={32} />
                    </div>
                    <h3 className="text-xl font-bold text-gray-700 mb-2">No items found</h3>
                    <p className="text-gray-400">Try adjusting your search or filter criteria.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {items.map(item => (
                        <ItemCard key={item._id} item={item} />
                    ))}
                </div>
            )}
        </div>
    );
};

export default Dashboard;

// frontend-angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { ItemCardComponent } from '../../components/item-card/item-card.component';
import { LucideAngularModule, Search, Filter, Compass } from 'lucide-angular';
import { firstValueFrom } from 'rxjs';
import { LostItem } from '../../services/item.service';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule, ItemCardComponent, LucideAngularModule],
  template: `
    <div class="animate-fade-in pb-20 pt-10 px-4 max-w-6xl mx-auto">
      <!-- Header -->
      <div class="mb-12 text-center max-w-2xl mx-auto">
        <div class="inline-flex items-center justify-center w-20 h-20 bg-primary-light rounded-full mb-6 animate-float shadow-sm">
          <lucide-icon [name]="CompassIcon" [size]="36" class="text-primary"></lucide-icon>
        </div>
        <h1 class="text-4xl md:text-5xl font-extrabold text-[#2b2d42] mb-4 tracking-tight">Community Board</h1>
        <p class="text-lg text-gray-500 font-semibold">Browse reported missing and found items around the community.</p>
      </div>

      <!-- Floating Filter & Search Pill -->
      <div class="bg-white/80 backdrop-blur-xl p-3 border-4 border-white rounded-[2rem] shadow-bubbly mb-12 flex flex-col md:flex-row gap-4 items-center justify-between sticky top-24 z-40 transition-all">
        <!-- Filter Tabs -->
        <div class="flex w-full md:w-auto p-1.5 bg-gray-50 rounded-full border-2 border-gray-100">
          <button *ngFor="let cat of ['All', 'Lost', 'Found']"
                  (click)="setFilter(cat)"
                  class="px-6 py-2.5 rounded-full text-sm font-extrabold transition-all border-none cursor-pointer flex-1 md:flex-none text-center"
                  [ngClass]="getFilterClass(cat)">
            {{ cat }}
          </button>
        </div>

        <!-- Search Bar -->
        <form (submit)="handleSearch($event)" class="relative w-full md:w-96 flex">
          <input type="text" placeholder="Search for items, locations, or tags..."
                 [(ngModel)]="searchTerm" name="searchTerm"
                 class="w-full bg-gray-50 border-2 border-transparent rounded-[1.5rem] py-3 pl-6 pr-14 text-sm font-semibold focus:border-primary focus:bg-white transition-all outline-none shadow-inner">
          <button type="submit" class="absolute right-2 top-1.5 p-2 bg-primary text-white rounded-full hover:scale-110 transition-transform border-none cursor-pointer shadow-md">
            <lucide-icon [name]="SearchIcon" [size]="18"></lucide-icon>
          </button>
        </form>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading; else itemsGrid" class="flex flex-col justify-center items-center py-20 gap-4">
        <div class="w-16 h-16 border-4 border-primary-light border-t-primary rounded-full animate-spin"></div>
        <p class="text-primary font-bold animate-pulse">Fetching items...</p>
      </div>

      <ng-template #itemsGrid>
        <!-- Empty State -->
        <div *ngIf="items.length === 0; else showItems" 
             class="text-center py-24 bg-white rounded-[3rem] border-4 border-dashed border-gray-100 flex flex-col items-center">
          <div class="bg-gray-50 w-24 h-24 rounded-[2rem] flex items-center justify-center mb-6 shadow-inner">
            <lucide-icon [name]="FilterIcon" [size]="40" class="text-gray-300"></lucide-icon>
          </div>
          <h3 class="text-2xl font-extrabold text-[#2b2d42] mb-3">No cute items found</h3>
          <p class="text-gray-500 font-medium text-lg">Try adjusting your search or filter criteria.</p>
          <button (click)="setFilter('All'); searchTerm=''" class="mt-8 btn-outline">Clear Filters</button>
        </div>

        <!-- Grid -->
        <ng-template #showItems>
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 animate-fade-in delay-100">
            <app-item-card *ngFor="let item of items" [item]="item" class="h-full"></app-item-card>
          </div>
        </ng-template>
      </ng-template>
    </div>
  `
})
export class DashboardComponent implements OnInit {
  private http = inject(HttpClient);
  
  items: LostItem[] = [];
  loading = true;
  filter = 'All';
  searchTerm = '';

  readonly CompassIcon = Compass;
  readonly SearchIcon = Search;
  readonly FilterIcon = Filter;

  ngOnInit() {
    this.fetchItems();
  }

  async fetchItems() {
    this.loading = true;
    try {
      let url = '/api/items';
      const params: any = {};
      if (this.filter !== 'All') params.category = this.filter;
      if (this.searchTerm) params.search = this.searchTerm;
      
      const queryParams = new URLSearchParams(params).toString();
      if (queryParams) url += `?${queryParams}`;

      const data = await firstValueFrom(this.http.get<LostItem[]>(url));
      this.items = data;
    } catch (error) {
      console.error('Failed to fetch items:', error);
    } finally {
      this.loading = false;
    }
  }

  setFilter(cat: string) {
    this.filter = cat;
    this.fetchItems();
  }

  handleSearch(e: Event) {
    e.preventDefault();
    this.fetchItems();
  }

  getFilterClass(cat: string) {
    if (this.filter !== cat) return 'text-gray-500 hover:text-gray-700';
    
    if (cat === 'Lost') return 'bg-[#ffeaf0] text-primary shadow-sm';
    if (cat === 'Found') return 'bg-[#eaf3ff] text-secondary shadow-sm';
    return 'bg-white text-gray-800 shadow-sm';
  }
}
