// frontend/src/pages/PostItem.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { UploadCloud, MapPin, Tag, Type, CalendarIcon } from 'lucide-react';

const PostItem = () => {
    const [formData, setFormData] = useState({
        title: '',
        description: '',
        category: 'Lost',
        location: '',
        date: new Date().toISOString().split('T')[0]
    });
    const [image, setImage] = useState(null);
    const [preview, setPreview] = useState(null);
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();
    const { user } = useAuth();

    if (!user) {
        return (
            <div className="text-center py-20 animate-fade-in">
                <h2 className="text-2xl font-bold text-gray-800">Please log in to post an item</h2>
                <button onClick={() => navigate('/login')} className="mt-4 btn-primary">Go to Login</button>
            </div>
        );
    }

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleImageChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            setImage(file);
            setPreview(URL.createObjectURL(file));
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);

        const data = new FormData();
        Object.keys(formData).forEach(key => data.append(key, formData[key]));
        if (image) data.append('image', image);

        try {
            const token = user.token;
            await axios.post('/api/items', data, {
                headers: {
                    'Content-Type': 'multipart/form-data',
                    Authorization: `Bearer ${token}`
                }
            });
            navigate('/dashboard');
        } catch (error) {
            console.error('Error posting item:', error);
            alert('Failed to post item. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto animate-fade-in pb-12">
            <div className="bg-white p-8 rounded-3xl subtle-shadow mt-6">
                <h1 className="text-3xl font-extrabold text-gray-800 mb-2">Report an Item</h1>
                <p className="text-gray-500 mb-8 border-b pb-6">Help the community by providing details about what you found or lost.</p>

                <form onSubmit={handleSubmit} className="space-y-6">
                    <div className="flex gap-4 p-1 bg-gray-50 rounded-xl mb-6">
                        <label className={`flex-1 text-center py-3 rounded-lg font-bold cursor-pointer transition-colors ${formData.category === 'Lost' ? 'bg-[var(--color-primary)] text-white shadow-md' : 'text-gray-500 hover:bg-gray-100'}`}>
                            <input type="radio" name="category" value="Lost" checked={formData.category === 'Lost'} onChange={handleChange} className="hidden" />
                            I Lost Something
                        </label>
                        <label className={`flex-1 text-center py-3 rounded-lg font-bold cursor-pointer transition-colors ${formData.category === 'Found' ? 'bg-[var(--color-secondary)] text-white shadow-md' : 'text-gray-500 hover:bg-gray-100'}`}>
                            <input type="radio" name="category" value="Found" checked={formData.category === 'Found'} onChange={handleChange} className="hidden" />
                            I Found Something
                        </label>
                    </div>

                    <div>
                        <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-1 ml-1"><Type size={16} /> Item Name</label>
                        <input type="text" name="title" required value={formData.title} onChange={handleChange} className="input-field" placeholder="e.g., Fluffy Orange Cat, Blue iPhone 13" />
                    </div>

                    <div>
                        <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-1 ml-1"><Tag size={16} /> Description</label>
                        <textarea name="description" required value={formData.description} onChange={handleChange} rows="3" className="input-field resize-none" placeholder="Provide helpful details..."></textarea>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-1 ml-1"><MapPin size={16} /> Location</label>
                            <input type="text" name="location" required value={formData.location} onChange={handleChange} className="input-field" placeholder="e.g., Central Park, Main St Cafe" />
                        </div>
                        <div>
                            <label className="flex items-center gap-2 text-sm font-semibold text-gray-700 mb-1 ml-1"><CalendarIcon size={16} /> Date</label>
                            <input type="date" name="date" required value={formData.date} onChange={handleChange} className="input-field text-gray-600" />
                        </div>
                    </div>

                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2 ml-1">Photo (Optional but helpful)</label>
                        <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-200 border-dashed rounded-2xl hover:border-[var(--color-primary)] transition-colors group relative overflow-hidden bg-gray-50">
                            {preview ? (
                                <div className="absolute inset-0 w-full h-full">
                                    <img src={preview} alt="Preview" className="w-full h-full object-cover" />
                                    <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                        <p className="text-white font-bold text-sm">Click to change</p>
                                    </div>
                                </div>
                            ) : (
                                <div className="space-y-1 justify-center text-center flex flex-col items-center">
                                    <UploadCloud className="mx-auto h-12 w-12 text-gray-400 group-hover:text-[var(--color-primary)] transition-colors" />
                                    <div className="flex text-sm text-gray-600">
                                        <span className="relative cursor-pointer rounded-md font-medium text-[var(--color-primary)] hover:text-[var(--color-primary-hover)] focus-within:outline-none">
                                            <span>Upload a file</span>
                                        </span>
                                        <p className="pl-1">or drag and drop</p>
                                    </div>
                                    <p className="text-xs text-gray-500">PNG, JPG, GIF up to 5MB</p>
                                </div>
                            )}
                            <input type="file" name="image" accept="image/*" onChange={handleImageChange} className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" />
                        </div>
                    </div>

                    <div className="pt-4">
                        <button type="submit" disabled={loading} className={`w-full py-4 text-lg btn-primary shadow-md ${loading ? 'opacity-70 cursor-not-allowed' : ''}`}>
                            {loading ? 'Posting...' : 'Post Item to Board ✨'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default PostItem;

// frontend-angular/src/app/pages/post-item/post-item.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ItemService } from '../../services/item.service';
import { LucideAngularModule, UploadCloud, MapPin, Tag, Type, Calendar } from 'lucide-angular';

@Component({
  selector: 'app-post-item',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div class="max-w-3xl mx-auto animate-fade-in pb-20 pt-10 px-4">
      
      <!-- Login Prompt -->
      <div *ngIf="!auth.user()" class="text-center py-20 bg-white rounded-[3rem] shadow-bubbly flex flex-col items-center">
        <div class="w-24 h-24 bg-primary-light rounded-[2rem] flex items-center justify-center mb-6 animate-float">
          <lucide-icon [name]="TypeIcon" [size]="40" class="text-primary"></lucide-icon>
        </div>
        <h2 class="text-3xl font-extrabold text-[#2b2d42] mb-4">Oops! You need to log in</h2>
        <p class="text-gray-500 font-medium mb-8">Please log in to your account to post a lost or found item.</p>
        <button (click)="router.navigate(['/login'])" class="btn-primary py-3 px-8 text-lg">Go to Login</button>
      </div>

      <!-- Main Form -->
      <div *ngIf="auth.user()" class="bubbly-card p-8 md:p-12 relative overflow-hidden">
        
        <!-- Decorative Header Blur -->
        <div class="absolute -top-20 -right-20 w-64 h-64 bg-primary-light/50 rounded-full blur-[3rem] pointer-events-none"></div>

        <div class="relative z-10">
          <h1 class="text-4xl font-extrabold text-[#2b2d42] mb-3">Report an Item ✨</h1>
          <p class="text-lg text-gray-500 font-medium mb-10 pb-8 border-b-2 border-gray-100">
            Help the community by sharing details about what you found or lost.
          </p>

          <form (submit)="handleSubmit($event)" class="space-y-8">
            
            <!-- Category Toggle (Segmented Control style) -->
            <div class="bg-gray-50 p-2 rounded-[2rem] flex gap-2 shadow-inner">
              <label class="flex-1 text-center py-4 rounded-[1.5rem] font-extrabold cursor-pointer transition-all duration-300 transform active:scale-95"
                     [ngClass]="formData.category === 'Lost' ? 'bg-primary text-white shadow-bubbly' : 'text-gray-400 hover:bg-gray-200/50 hover:text-gray-600'">
                <input type="radio" name="category" value="Lost" [(ngModel)]="formData.category" class="hidden">
                I Lost Something
              </label>
              <label class="flex-1 text-center py-4 rounded-[1.5rem] font-extrabold cursor-pointer transition-all duration-300 transform active:scale-95"
                     [ngClass]="formData.category === 'Found' ? 'bg-secondary text-white shadow-bubbly' : 'text-gray-400 hover:bg-gray-200/50 hover:text-gray-600'">
                <input type="radio" name="category" value="Found" [(ngModel)]="formData.category" class="hidden">
                I Found Something
              </label>
            </div>

            <!-- Title & Description -->
            <div class="space-y-6">
              <div class="group">
                <label class="flex items-center gap-2 text-sm font-extrabold text-gray-700 mb-2 ml-2 uppercase tracking-wide">
                  <lucide-icon [name]="TypeIcon" [size]="16" class="text-primary group-focus-within:text-primary transition-colors"></lucide-icon> 
                  Item Name
                </label>
                <input type="text" name="title" required [(ngModel)]="formData.title" 
                       class="input-bubbly" placeholder="e.g., Fluffy Orange Cat, Blue iPhone 13">
              </div>

              <div class="group">
                <label class="flex items-center gap-2 text-sm font-extrabold text-gray-700 mb-2 ml-2 uppercase tracking-wide">
                  <lucide-icon [name]="TagIcon" [size]="16" class="text-primary hover:text-primary transition-colors"></lucide-icon> 
                  Description
                </label>
                <textarea name="description" required [(ngModel)]="formData.description" 
                          rows="4" class="input-bubbly resize-none" placeholder="Provide helpful details..."></textarea>
              </div>
            </div>

            <!-- Location & Date -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 bg-gray-50/50 p-6 rounded-[2rem] border-2 border-gray-50">
              <div class="group">
                <label class="flex items-center gap-2 text-sm font-extrabold text-gray-700 mb-2 ml-2 uppercase tracking-wide">
                  <lucide-icon [name]="MapIcon" [size]="16" class="text-secondary"></lucide-icon> Location
                </label>
                <input type="text" name="location" required [(ngModel)]="formData.location" 
                       class="input-bubbly bg-white" placeholder="e.g., Central Park">
              </div>
              <div class="group">
                <label class="flex items-center gap-2 text-sm font-extrabold text-gray-700 mb-2 ml-2 uppercase tracking-wide">
                  <lucide-icon [name]="CalendarIcon" [size]="16" class="text-secondary"></lucide-icon> Date
                </label>
                <input type="date" name="date" required [(ngModel)]="formData.date" 
                       class="input-bubbly bg-white text-gray-600">
              </div>
            </div>

            <!-- Photo Upload -->
            <div>
              <label class="block text-sm font-extrabold text-gray-700 mb-3 ml-2 uppercase tracking-wide">Photo (Optional but super helpful)</label>
              <div class="relative group mt-1 flex justify-center px-6 pt-10 pb-12 border-4 border-dashed border-primary-light/50 bg-primary-light/10 rounded-[2rem] hover:border-primary hover:bg-primary-light/20 transition-all cursor-pointer overflow-hidden text-center">
                
                <div *ngIf="preview" class="absolute inset-0 w-full h-full p-2">
                  <img [src]="preview" alt="Preview" class="w-full h-full object-cover rounded-2xl shadow-sm">
                  <div class="absolute inset-2 rounded-2xl bg-black/50 flex flex-col items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-sm">
                    <lucide-icon [name]="UploadIcon" [size]="32" class="text-white mb-2"></lucide-icon>
                    <p class="text-white font-extrabold text-sm">Tap to change image</p>
                  </div>
                </div>
                
                <div *ngIf="!preview" class="space-y-3 flex flex-col items-center">
                  <div class="w-16 h-16 bg-white rounded-full shadow-sm flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                    <lucide-icon [name]="UploadIcon" [size]="32"></lucide-icon>
                  </div>
                  <div class="text-lg text-gray-600 font-bold">
                    <span class="text-primary">Upload a cute photo</span> or drag and drop
                  </div>
                  <p class="text-sm font-semibold text-gray-400 bg-white px-3 py-1 rounded-full shadow-sm">PNG, JPG up to 5MB</p>
                </div>
                
                <input type="file" name="image" accept="image/*" (change)="handleImageChange($event)" 
                       class="absolute inset-0 w-full h-full opacity-0 cursor-pointer outline-none">
              </div>
            </div>

            <!-- Submit Button -->
            <div class="pt-6 border-t-2 border-gray-100">
              <button type="submit" [disabled]="loading" 
                      class="w-full py-5 text-xl btn-primary shadow-bubbly flex justify-center items-center gap-3">
                <div *ngIf="loading" class="w-6 h-6 border-4 border-white border-t-transparent rounded-full animate-spin"></div>
                <span *ngIf="!loading">Post Item to Board ✨</span>
                <span *ngIf="loading">Publishing...</span>
              </button>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  `
})
export class PostItemComponent {
  auth = inject(AuthService);
  private itemService = inject(ItemService);
  router = inject(Router);

  formData = {
    title: '',
    description: '',
    category: 'Lost',
    location: '',
    date: new Date().toISOString().split('T')[0]
  };
  image: File | null = null;
  preview: string | null = null;
  loading = false;

  readonly TypeIcon = Type;
  readonly TagIcon = Tag;
  readonly MapIcon = MapPin;
  readonly CalendarIcon = Calendar;
  readonly UploadIcon = UploadCloud;

  handleImageChange(e: any) {
    const file = e.target.files[0];
    if (file) {
      this.image = file;
      this.preview = URL.createObjectURL(file);
    }
  }

  async handleSubmit(e: Event) {
    e.preventDefault();
    this.loading = true;

    const data = new FormData();
    Object.keys(this.formData).forEach(key => data.append(key, (this.formData as any)[key]));
    if (this.image) data.append('image', this.image);

    try {
      await this.itemService.createItem(data);
      this.router.navigate(['/dashboard']);
    } catch (error) {
      console.error('Error posting item:', error);
      alert('Failed to post item. Please try again.');
    } finally {
      this.loading = false;
    }
  }
}
