// frontend-angular/src/app/components/item-card/item-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { LostItem } from '../../services/item.service';
import { LucideAngularModule, MapPin, Calendar, Tag, ArrowRight } from 'lucide-angular';

@Component({
  selector: 'app-item-card',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule],
  template: `
    <div class="bubbly-card h-full flex flex-col p-4 group cursor-pointer relative" [routerLink]="['/item', item._id]">
      <!-- Image Container (Polaroid style) -->
      <div class="relative rounded-2xl overflow-hidden mb-4 aspect-[4/3] bg-gray-100 shadow-inner">
        <img [src]="item.image || 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=2040&auto=format&fit=crop'" 
             class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
             [alt]="item.title">
             
        <!-- Cute Badges Over Image -->
        <div class="absolute top-3 right-3 flex flex-col gap-2 items-end">
          <span class="shadow-sm"
                [ngClass]="item.category === 'Lost' ? 'badge-lost' : 'badge-found'">
            {{ item.category }}
          </span>
          <span class="shadow-sm px-3 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wider backdrop-blur-md bg-white/80" 
                [ngClass]="item.status === 'Claimed' ? 'text-green-600 border border-green-200' : 'text-orange-500 border border-orange-200'">
            {{ item.status }}
          </span>
        </div>
      </div>
      
      <!-- Content -->
      <div class="flex-grow flex flex-col">
        <h3 class="text-xl font-extrabold text-[#2b2d42] mb-3 line-clamp-1 group-hover:text-primary transition-colors">
          {{ item.title }}
        </h3>
        
        <div class="space-y-2 mb-4">
          <div class="flex items-center gap-2 text-gray-500 text-sm font-semibold bg-gray-50 px-3 py-1.5 rounded-xl w-fit">
            <lucide-icon [name]="MapIcon" [size]="14" class="text-primary-hover"></lucide-icon>
            <span class="truncate max-w-[150px]">{{ item.location }}</span>
          </div>
          <div class="flex items-center gap-2 text-gray-500 text-sm font-semibold px-1">
            <lucide-icon [name]="CalendarIcon" [size]="14"></lucide-icon>
            <span>{{ item.date | date:'mediumDate' }}</span>
          </div>
        </div>
        
        <!-- Footer / Owner -->
        <div class="pt-4 mt-auto border-t border-gray-100 flex items-center justify-between">
          <div class="flex items-center gap-3">
            <div class="w-8 h-8 rounded-full bg-secondary-light text-secondary flex items-center justify-center font-extrabold shadow-sm border-2 border-white overflow-hidden">
               <img *ngIf="item.owner?.avatar" [src]="item.owner.avatar" class="w-full h-full object-cover">
               <span *ngIf="!item.owner?.avatar">{{ item.owner?.name?.charAt(0) || 'U' }}</span>
            </div>
            <span class="text-xs font-bold text-gray-600 truncate max-w-[80px]">{{ item.owner?.name || 'Unknown' }}</span>
          </div>
          <div class="w-8 h-8 rounded-full bg-primary-light text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-white transition-colors duration-300">
            <lucide-icon [name]="ArrowRightIcon" [size]="16"></lucide-icon>
          </div>
        </div>
      </div>
    </div>
  `
})
export class ItemCardComponent {
  @Input({ required: true }) item!: LostItem;

  readonly TagIcon = Tag;
  readonly MapIcon = MapPin;
  readonly CalendarIcon = Calendar;
  readonly ArrowRightIcon = ArrowRight;
}

// frontend/src/components/ItemCard.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { MapPin, Calendar, Heart } from 'lucide-react';
import { format } from 'date-fns';

const ItemCard = ({ item }) => {
    const isLost = item.category === 'Lost';

    return (
        <div className="bg-white rounded-3xl subtle-shadow overflow-hidden group hover:-translate-y-1 transition-transform duration-300 border border-transparent hover:border-gray-100 pb-4">
            <div className="relative h-48 w-full bg-gray-100 overflow-hidden">
                {item.image ? (
                    <img
                        src={item.image}
                        alt={item.title}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                ) : (
                    <div className="w-full h-full flex flex-col items-center justify-center text-gray-400">
                        <Heart size={32} className="mb-2 opacity-50" />
                        <span className="text-sm">No photo</span>
                    </div>
                )}
                <div className={`absolute top-3 right-3 px-3 py-1 rounded-full text-xs font-bold shadow-sm ${isLost ? 'bg-[#ffeaf0] text-[var(--color-primary)]' : 'bg-[#eaf3ff] text-[var(--color-secondary)]'
                    }`}>
                    {item.category}
                </div>
            </div>

            <div className="p-5">
                <h3 className="text-xl font-bold text-gray-800 mb-1 truncate">{item.title}</h3>

                <div className="flex items-center text-sm text-gray-500 mb-2 mt-3">
                    <MapPin size={16} className="mr-1 text-gray-400" />
                    <span className="truncate">{item.location}</span>
                </div>

                <div className="flex items-center text-sm text-gray-500 mb-4">
                    <Calendar size={16} className="mr-1 text-gray-400" />
                    <span>{format(new Date(item.date), 'MMM dd, yyyy')}</span>
                </div>

                <div className="flex justify-between items-center mt-4">
                    <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center text-xs font-bold text-gray-600 overflow-hidden">
                            {item.owner?.avatar ? (
                                <img src={item.owner.avatar} alt="Owner preview" className="w-full h-full object-cover" />
                            ) : (
                                item.owner?.name?.charAt(0).toUpperCase() || 'U'
                            )}
                        </div>
                        <span className="text-sm font-medium text-gray-600 truncate max-w-[100px]">{item.owner?.name || 'User'}</span>
                    </div>

                    <Link to={`/item/${item._id}`} className={`px-4 py-1.5 rounded-full text-sm font-semibold transition-colors ${isLost ? 'bg-[var(--color-primary)] text-white hover:bg-[var(--color-primary-hover)]' : 'bg-[var(--color-secondary)] text-white hover:bg-blue-400'
                        }`}>
                        View Details
                    </Link>
                </div>

                {item.status === 'Claimed' && (
                    <div className="absolute top-0 left-0 w-full h-full bg-white/80 backdrop-blur-[2px] z-10 flex items-center justify-center">
                        <span className="bg-green-100 text-green-700 font-bold px-4 py-2 rounded-full shadow-sm transform -rotate-12 border border-green-200 text-lg">
                            Resolved ✨
                        </span>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ItemCard;
