// frontend-angular/src/app/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { 
  LucideAngularModule, 
  Search, 
  Home, 
  PlusCircle, 
  MessageCircle, 
  LogOut, 
  User 
} from 'lucide-angular';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, LucideAngularModule],
  template: `
    <div class="fixed top-4 left-0 w-full z-50 px-4 pointer-events-none">
      <nav class="container mx-auto max-w-5xl floating-glass-nav pointer-events-auto transition-all">
        <div class="px-6 h-16 flex items-center justify-between">
          <!-- Brand -->
          <a routerLink="/" class="text-2xl font-extrabold flex items-center gap-2 text-primary" style="text-decoration: none;">
            <div class="w-10 h-10 bg-primary-light rounded-full flex items-center justify-center transition-transform hover:scale-110">
              <lucide-icon [name]="SearchIcon" [size]="20" class="text-primary"></lucide-icon>
            </div>
            <span class="tracking-tight">FindIt</span>
          </a>
          
          <!-- Navigation Links -->
          <div class="flex items-center gap-2 sm:gap-4">
            <a routerLink="/" routerLinkActive="bg-white text-primary shadow-sm" [routerLinkActiveOptions]="{exact: true}" 
               class="px-4 py-2 rounded-full text-gray-500 hover:text-primary hover:bg-white hover:shadow-sm flex items-center gap-2 transition-all font-bold" style="text-decoration: none;">
              <lucide-icon [name]="HomeIcon" [size]="18"></lucide-icon>
              <span class="hidden sm:inline">Home</span>
            </a>
            
            <ng-container *ngIf="auth.user() as user; else guestLinks">
              <a routerLink="/dashboard" routerLinkActive="bg-white text-primary shadow-sm" 
                 class="px-4 py-2 rounded-full text-gray-500 hover:text-primary hover:bg-white hover:shadow-sm flex items-center gap-2 transition-all font-bold" style="text-decoration: none;">
                <lucide-icon [name]="SearchIcon" [size]="18"></lucide-icon>
                <span class="hidden sm:inline">Browse</span>
              </a>
              <a routerLink="/post" routerLinkActive="bg-white text-primary shadow-sm" 
                 class="px-4 py-2 rounded-full text-gray-500 hover:text-primary hover:bg-white hover:shadow-sm flex items-center gap-2 transition-all font-bold" style="text-decoration: none;">
                <lucide-icon [name]="PlusCircleIcon" [size]="18"></lucide-icon>
                <span class="hidden sm:inline">Post</span>
              </a>
              
              <div class="h-6 w-px bg-gray-200 mx-2 hidden sm:block"></div>
              
              <div class="flex items-center gap-3">
                <div class="w-9 h-9 rounded-full bg-secondary text-white flex items-center justify-center font-bold shadow-sm border-2 border-white">
                  {{ user.name.charAt(0).toUpperCase() }}
                </div>
                <button (click)="auth.logout()" class="p-2 rounded-full text-gray-400 hover:text-primary hover:bg-white hover:shadow-sm transition-all bg-transparent border-none cursor-pointer" title="Logout">
                  <lucide-icon [name]="LogOutIcon" [size]="18"></lucide-icon>
                </button>
              </div>
            </ng-container>
  
            <ng-template #guestLinks>
              <div class="flex items-center gap-2 sm:gap-3 pl-2 sm:pl-4 border-l border-gray-100">
                <a routerLink="/login" class="text-gray-500 hover:text-primary font-bold px-3 py-2 transition-colors" style="text-decoration: none;">
                  Log In
                </a>
                <a routerLink="/register" class="btn-primary text-sm px-5 py-2">
                  Sign Up
                </a>
              </div>
            </ng-template>
          </div>
        </div>
      </nav>
    </div>
  `
})
export class NavbarComponent {
  auth = inject(AuthService);

  readonly SearchIcon = Search;
  readonly HomeIcon = Home;
  readonly PlusCircleIcon = PlusCircle;
  readonly MessageCircleIcon = MessageCircle;
  readonly LogOutIcon = LogOut;
  readonly UserIcon = User;
}

// frontend/src/components/Navbar.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Search, Home, PlusCircle, MessageCircle, LogOut, User } from 'lucide-react';

const Navbar = () => {
    const { user, logout } = useAuth();

    return (
        <nav className="bg-white subtle-shadow sticky top-0 z-50">
            <div className="container mx-auto px-4 max-w-5xl h-16 flex items-center justify-between">
                <Link to="/" className="text-2xl font-bold flex items-center gap-2 text-[var(--color-primary)]">
                    <Search size={28} />
                    <span>FindIt</span>
                </Link>
                <div className="flex items-center gap-6">
                    <Link to="/" className="text-gray-600 hover:text-[var(--color-primary)] flex items-center gap-1 transition-colors">
                        <Home size={20} /> <span className="hidden sm:inline">Home</span>
                    </Link>
                    {user ? (
                        <>
                            <Link to="/dashboard" className="text-gray-600 hover:text-[var(--color-primary)] flex items-center gap-1 transition-colors">
                                <Search size={20} /> <span className="hidden sm:inline">Browse</span>
                            </Link>
                            <Link to="/post" className="text-gray-600 hover:text-[var(--color-primary)] flex items-center gap-1 transition-colors">
                                <PlusCircle size={20} /> <span className="hidden sm:inline">Post Item</span>
                            </Link>
                            {/* Note: We will implement an inbox mapping later, redirecting to a dummy chat for now */}
                            <Link to="/chat/inbox" className="text-gray-600 hover:text-[var(--color-primary)] flex items-center gap-1 transition-colors">
                                <MessageCircle size={20} /> <span className="hidden sm:inline">Messages</span>
                            </Link>
                            <div className="flex items-center gap-3 ml-2 pl-4 border-l border-gray-200">
                                <div className="w-8 h-8 rounded-full bg-[var(--color-secondary)] text-white flex items-center justify-center font-bold">
                                    {user.name.charAt(0).toUpperCase()}
                                </div>
                                <button onClick={logout} className="text-gray-500 hover:text-red-500 transition-colors" title="Logout">
                                    <LogOut size={20} />
                                </button>
                            </div>
                        </>
                    ) : (
                        <div className="flex gap-3">
                            <Link to="/login" className="text-gray-600 hover:text-[var(--color-primary)] font-medium px-2 py-1">
                                Log In
                            </Link>
                            <Link to="/register" className="btn-primary text-sm px-4 py-1.5 flex items-center gap-1 shadow-sm hover:shadow-md transition-shadow">
                                Sign Up
                            </Link>
                        </div>
                    )}
                </div>
            </div>
        </nav>
    );
};

export default Navbar;
