// frontend-angular/src/app/pages/item-detail/item-detail.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ItemService, LostItem } from '../../services/item.service';
import { AuthService } from '../../services/auth.service';
import { HttpClient } from '@angular/common/http';
import { LucideAngularModule, MapPin, Calendar, Heart, Share2, MessageCircle, AlertCircle, Info } from 'lucide-angular';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-item-detail',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule],
  template: `
    <div class="max-w-5xl mx-auto animate-fade-in pb-20 pt-10 px-4">
      <!-- Loading State -->
      <div *ngIf="loading" class="flex flex-col justify-center items-center h-64 gap-4">
        <div class="w-16 h-16 border-4 border-primary-light border-t-primary rounded-full animate-spin"></div>
        <p class="text-primary font-bold animate-pulse">Loading cute details...</p>
      </div>

      <!-- Not Found State -->
      <div *ngIf="!loading && !item" class="text-center py-20 bg-white rounded-[3rem] border-4 border-dashed border-gray-100 flex flex-col items-center">
        <div class="bg-gray-50 w-24 h-24 rounded-[2rem] flex items-center justify-center mb-6 shadow-inner">
          <lucide-icon [name]="HeartIcon" [size]="40" class="text-gray-300"></lucide-icon>
        </div>
        <h3 class="text-2xl font-extrabold text-[#2b2d42] mb-3">Item not found. 😿</h3>
        <button routerLink="/dashboard" class="mt-8 btn-outline">Back to Board</button>
      </div>

      <!-- Detail View -->
      <div *ngIf="!loading && item" class="flex flex-col lg:flex-row gap-8">
        
        <!-- Massive Rounded Image Container -->
        <div class="lg:w-1/2 relative">
          <div class="sticky top-24 rounded-[3rem] overflow-hidden shadow-bubbly bg-white border-8 border-white aspect-[4/5] sm:aspect-square lg:aspect-[4/5]">
            <img *ngIf="item.image" [src]="item.image" [alt]="item.title" class="w-full h-full object-cover transition-transform duration-700 hover:scale-105">
            <div *ngIf="!item.image" class="w-full h-full bg-gray-50 flex flex-col items-center justify-center text-gray-400">
              <lucide-icon [name]="HeartIcon" [size]="64" class="mb-4 opacity-20 animate-pulse"></lucide-icon>
              <span class="font-extrabold text-xl opacity-50">No cute photo provided</span>
            </div>
            
            <!-- Floating Category Badge -->
            <div class="absolute top-6 left-6 px-6 py-2 rounded-full font-extrabold shadow-lg backdrop-blur-md"
                 [ngClass]="item.category === 'Lost' ? 'bg-primary/90 text-white' : 'bg-secondary/90 text-white'">
              {{ item.category }}
            </div>
            <!-- Floating Status Badge -->
            <div class="absolute top-6 right-6 px-4 py-2 rounded-full font-extrabold shadow-lg backdrop-blur-md bg-white/90"
                 [ngClass]="item.status === 'Claimed' ? 'text-green-500' : 'text-orange-400'">
              {{ item.status }} ✨
            </div>
          </div>
        </div>

        <!-- Info Bubbles -->
        <div class="lg:w-1/2 flex flex-col gap-6">
          <div class="flex justify-between items-start">
            <h1 class="text-4xl sm:text-5xl font-extrabold text-[#2b2d42] leading-tight tracking-tight">{{ item.title }}</h1>
          </div>

          <!-- Bubbly Info Cards Row -->
          <div class="grid grid-cols-2 gap-4">
            <div class="bg-white rounded-[2rem] p-5 shadow-sm border border-gray-50 flex flex-col gap-2 hover:shadow-md transition-shadow">
              <div class="w-10 h-10 rounded-full bg-secondary-light text-secondary flex items-center justify-center">
                <lucide-icon [name]="MapIcon" [size]="20"></lucide-icon>
              </div>
              <span class="text-sm font-bold text-gray-400 uppercase tracking-widest">Location</span>
              <span class="font-bold text-gray-700">{{ item.location }}</span>
            </div>
            
            <div class="bg-white rounded-[2rem] p-5 shadow-sm border border-gray-50 flex flex-col gap-2 hover:shadow-md transition-shadow">
              <div class="w-10 h-10 rounded-full bg-primary-light text-primary flex items-center justify-center">
                <lucide-icon [name]="CalendarIcon" [size]="20"></lucide-icon>
              </div>
              <span class="text-sm font-bold text-gray-400 uppercase tracking-widest">Date {{ item.category === 'Lost' ? 'Lost' : 'Found' }}</span>
              <span class="font-bold text-gray-700">{{ item.date | date:'longDate' }}</span>
            </div>
          </div>

          <!-- Description Bubble -->
          <div class="bubbly-card bg-white mt-2">
            <h3 class="font-extrabold text-gray-800 text-xl mb-4 flex items-center gap-2">
              <lucide-icon [name]="InfoIcon" [size]="24" class="text-accent-peach"></lucide-icon>
              Details
            </h3>
            <p class="text-gray-600 font-medium leading-relaxed whitespace-pre-line text-lg">
              {{ item.description }}
            </p>
          </div>

          <!-- Interaction Section -->
          <div class="mt-auto bg-[#f8fafc] rounded-[2rem] p-6 border-2 border-white shadow-sm flex flex-col gap-6">
            <!-- Owner Bubble -->
            <div class="flex items-center gap-4 bg-white p-3 rounded-full shadow-sm max-w-fit pr-6">
              <div class="w-12 h-12 rounded-full bg-accent-mint text-[#2b2d42] flex items-center justify-center font-extrabold overflow-hidden shadow-inner text-xl">
                <img *ngIf="item.owner.avatar" [src]="item.owner.avatar" class="w-full h-full object-cover">
                <span *ngIf="!item.owner.avatar">{{ item.owner.name.charAt(0).toUpperCase() }}</span>
              </div>
              <div>
                <p class="text-gray-400 font-bold text-xs uppercase tracking-wider mb-0.5">Posted by</p>
                <p class="font-extrabold text-[#2b2d42] leading-none text-lg">{{ item.owner.name }}</p>
              </div>
            </div>

            <!-- Action Buttons -->
            <ng-container *ngIf="auth.user() as currentUser; else guestView">
              <button *ngIf="currentUser._id !== item.owner._id && item.status !== 'Claimed'"
                      (click)="router.navigate(['/chat', item.owner._id], { queryParams: { itemId: item._id } })"
                      class="btn-primary py-4 text-xl w-full shadow-bubbly animate-pulse">
                <lucide-icon [name]="MessageIcon" [size]="24"></lucide-icon>
                Chat with {{ item.owner.name.split(' ')[0] }}
              </button>

              <div *ngIf="currentUser._id === item.owner._id" class="flex flex-col sm:flex-row gap-4 w-full">
                <button (click)="handleStatusUpdate()" 
                        class="btn-secondary py-3 flex-1 font-extrabold border-none cursor-pointer">
                  Mark as {{ item.status === 'Unclaimed' ? 'Claimed ✨' : 'Unclaimed' }}
                </button>
                <button (click)="handleDelete()" 
                        class="btn-outline border-red-200 text-red-500 hover:bg-red-50 hover:border-red-500 hover:text-red-500 py-3 font-extrabold">
                  Delete
                </button>
              </div>
            </ng-container>

            <!-- Guest View -->
            <ng-template #guestView>
              <div class="text-center p-6 bg-primary-light/30 rounded-3xl border border-primary-light">
                <p class="text-gray-600 font-bold mb-3">Want to help return this item?</p>
                <a routerLink="/login" class="btn-primary inline-flex">Log in to Chat</a>
              </div>
            </ng-template>
          </div>

        </div>
      </div>
    </div>
  `
})
export class ItemDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private itemService = inject(ItemService);
  private http = inject(HttpClient);
  auth = inject(AuthService);
  router = inject(Router);

  item: LostItem | null = null;
  loading = true;

  readonly HeartIcon = Heart;
  readonly ShareIcon = Share2;
  readonly AlertIcon = AlertCircle;
  readonly MapIcon = MapPin;
  readonly CalendarIcon = Calendar;
  readonly MessageIcon = MessageCircle;
  readonly InfoIcon = Info;

  ngOnInit() {
    this.loadItem();
  }

  async loadItem() {
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) return;

    try {
      this.item = await this.itemService.getItemById(id);
    } catch (error) {
      console.error('Failed to fetch item:', error);
    } finally {
      this.loading = false;
    }
  }

  async handleStatusUpdate() {
    if (!this.item || !this.item._id) return;
    try {
      const dataToUpdate = { status: this.item.status === 'Unclaimed' ? 'Claimed' : 'Unclaimed' };
      const token = this.auth.token;
      const updatedItem = await firstValueFrom(this.http.put<LostItem>(`/api/items/${this.item._id}`, dataToUpdate, {
        headers: { Authorization: `Bearer ${token}` }
      }));
      this.item.status = updatedItem.status;
    } catch (error) {
      console.error('Failed to update status:', error);
    }
  }

  async handleDelete() {
    if (!this.item || !this.item._id) return;
    if (window.confirm('Are you sure you want to delete this listing?')) {
      try {
        const token = this.auth.token;
        await firstValueFrom(this.http.delete(`/api/items/${this.item._id}`, {
          headers: { Authorization: `Bearer ${token}` }
        }));
        this.router.navigate(['/dashboard']);
      } catch (error) {
        console.error('Failed to delete:', error);
      }
    }
  }
}

// frontend/src/pages/ItemDetail.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { MapPin, Calendar, Heart, Share2, MessageCircle, AlertCircle } from 'lucide-react';
import { format } from 'date-fns';

const ItemDetail = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const [item, setItem] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchItem = async () => {
            try {
                const { data } = await axios.get(`/api/items/${id}`);
                setItem(data);
            } catch (error) {
                console.error('Failed to fetch item:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchItem();
    }, [id]);

    const handleStatusUpdate = async () => {
        try {
            const dataToUpdate = { status: item.status === 'Unclaimed' ? 'Claimed' : 'Unclaimed' };
            const { data } = await axios.put(`/api/items/${id}`, dataToUpdate, {
                headers: { Authorization: `Bearer ${user.token}` }
            });
            setItem({ ...item, status: data.status });
        } catch (error) {
            console.error('Failed to update status:', error);
            alert('Could not update status.');
        }
    };

    const handleDelete = async () => {
        if (window.confirm('Are you sure you want to delete this listing?')) {
            try {
                await axios.delete(`/api/items/${id}`, {
                    headers: { Authorization: `Bearer ${user.token}` }
                });
                navigate('/dashboard');
            } catch (error) {
                console.error('Failed to delete:', error);
                alert('Could not delete item.');
            }
        }
    };

    if (loading) return (
        <div className="flex justify-center items-center h-64">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[var(--color-primary)]"></div>
        </div>
    );

    if (!item) return <div className="text-center py-20 text-xl font-bold text-gray-600">Item not found. 😿</div>;

    const isOwner = user && user._id === item.owner._id;
    const isLost = item.category === 'Lost';

    return (
        <div className="max-w-4xl mx-auto animate-fade-in pb-12 mt-6">
            <div className="bg-white rounded-3xl subtle-shadow overflow-hidden flex flex-col md:flex-row border border-gray-50">
                {/* Image Section */}
                <div className="md:w-1/2 bg-gray-100 flex items-center justify-center relative min-h-[300px]">
                    {item.image ? (
                        <img src={item.image} alt={item.title} className="w-full h-full object-cover" />
                    ) : (
                        <div className="text-gray-400 flex flex-col items-center">
                            <Heart size={48} className="mb-4 opacity-30" />
                            <span className="font-medium text-lg">No image provided</span>
                        </div>
                    )}
                    <div className={`absolute top-4 left-4 px-4 py-1.5 rounded-full font-bold shadow-md ${isLost ? 'bg-[#ffeaf0] text-[var(--color-primary)]' : 'bg-[#eaf3ff] text-[var(--color-secondary)]'
                        }`}>
                        {item.category}
                    </div>
                </div>

                {/* Info Section */}
                <div className="md:w-1/2 p-8 flex flex-col">
                    <div className="flex justify-between items-start mb-2">
                        <h1 className="text-3xl font-extrabold text-gray-800 leading-tight">{item.title}</h1>
                        <button className="text-gray-400 hover:text-gray-600 bg-gray-100 p-2 rounded-full transition-colors"><Share2 size={20} /></button>
                    </div>

                    <div className="flex flex-col gap-3 mb-6 mt-4 pb-6 border-b border-gray-100">
                        <div className="flex items-center text-gray-600 bg-gray-50 rounded-lg p-2 px-3 w-fit">
                            <AlertCircle size={18} className="mr-2 text-[var(--color-secondary)]" />
                            <span className="font-bold mr-2 text-gray-700">Status:</span>
                            <span className={`font-semibold ${item.status === 'Claimed' ? 'text-green-500' : 'text-orange-400'}`}>{item.status}</span>
                        </div>
                        <div className="flex items-center text-gray-600">
                            <MapPin size={18} className="mr-2 text-gray-400" /> <span className="font-semibold text-gray-700 mr-2">Location:</span> {item.location}
                        </div>
                        <div className="flex items-center text-gray-600">
                            <Calendar size={18} className="mr-2 text-gray-400" /> <span className="font-semibold text-gray-700 mr-2">Date {isLost ? 'Lost' : 'Found'}:</span> {format(new Date(item.date), 'MMMM dd, yyyy')}
                        </div>
                    </div>

                    <div className="mb-8 flex-grow">
                        <h3 className="font-bold text-gray-800 text-lg mb-2">Description</h3>
                        <p className="text-gray-600 leading-relaxed whitespace-pre-line bg-gray-50 p-4 rounded-xl text-sm border border-gray-100">{item.description}</p>
                    </div>

                    {/* Action Buttons */}
                    <div className="mt-auto">
                        <div className="flex items-center justify-between bg-gray-50 p-3 rounded-2xl border border-gray-100 mb-4">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-full bg-[var(--color-secondary)] text-white flex items-center justify-center font-bold">
                                    {item.owner.avatar ? <img src={item.owner.avatar} className="w-full h-full rounded-full" /> : item.owner.name.charAt(0).toUpperCase()}
                                </div>
                                <div className="text-sm">
                                    <p className="text-gray-500 font-medium leading-none mb-1">Posted by</p>
                                    <p className="font-bold text-gray-800">{item.owner.name}</p>
                                </div>
                            </div>
                        </div>

                        {!isOwner && user && item.status !== 'Claimed' && (
                            <button onClick={() => navigate(`/chat/${item.owner._id}?itemId=${item._id}`)} className="w-full btn-primary py-3 text-lg flex items-center justify-center gap-2 shadow-md">
                                <MessageCircle size={22} /> Contact {item.owner.name.split(' ')[0]}
                            </button>
                        )}
                        {!user && (
                            <p className="text-center text-sm text-gray-500 bg-gray-50 p-4 rounded-xl">
                                Please <button onClick={() => navigate('/login')} className="text-[var(--color-primary)] font-bold hover:underline">log in</button> to contact the owner.
                            </p>
                        )}

                        {isOwner && (
                            <div className="flex justify-between mt-4">
                                <button onClick={handleStatusUpdate} className="bg-green-100 text-green-700 hover:bg-green-200 font-bold py-2.5 px-6 rounded-xl transition-colors w-1/2 mr-2">
                                    Mark as {item.status === 'Unclaimed' ? 'Claimed ✨' : 'Unclaimed'}
                                </button>
                                <button onClick={handleDelete} className="bg-red-50 text-red-600 hover:bg-red-100 font-bold py-2.5 px-6 rounded-xl transition-colors w-1/2 ml-2">
                                    Delete Post
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ItemDetail;
